services:
  db:
    image: postgres:15-alpine
    container_name: todos-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos
    ports:
      - "5432:5432"
    volumes:
      - todos_pgdata:/var/lib/postgresql/data
volumes:
  todos_pgdata:
